### ISSUE TITLE
Suddenly cant import created elu files (created with this addon)

### ISSUE THREAD

**Issue by bbgoose92** [Krunklehorn/io-scene-gzrs2#2]
reinstalled the plugin, reinstalled blender same issue.
worked for weeks but now even directly exporting an elu from the original blender project files, then trying to import that fails with this error. 

![Untitled](https://github.com/user-attachments/assets/546f3a1e-1ab9-4d30-a7cf-899f979dcd92)
in case it matters- im running blender 4.2.1 on windows 11.

**Comment by Krunklehorn** [comment]
Thanks for the bug report. I wasn't able to replicate this on my end.

Please add me on Discord and send me the .elu you're having trouble with: Krunk#6051

**Comment by Krunklehorn** [comment]
Solved as part of v0.9.4
